feat(component): add unread message notification
ruang-guru/sendbird-uikit-react pull request #14
Opened 2021-10-14 04:46 UTC by fauzanlinnas

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match with your own requirements.

## Related Issue

[RKLS-936](https://ruanggguru.atlassian.net/browse/RKLS-936)

## Description Of Changes

- Change `Notification` component
- Add `Unread Notification` story

![Screen Shot 2021-10-14 at 11 45 40](https://user-images.githubusercontent.com/26358930/137253603-1bae3eb0-931d-4c06-b027-e7cb151d8d3b.png)

2021-10-14 04:56 UTC, dskusuma requested changes

2021-10-14 04:56 UTC, dskusuma commented on src/rogu/smart-components/Conversation/components/Notification.jsx
> +  timeArray.splice(1, 0, stringSet.CHANNEL__MESSAGE_LIST__NOTIFICATION__ON);
@fauzanlinnas kira-kira di bagian ini bisa ditambahin komentar ga ya? inputannya apa dan nanti hasilnya apa? kalau baca sekilas butuh trace lagi 😅

2021-10-14 05:59 UTC, suliskh commented
Have you checked the click-behaviour, Mas @fauzanlinnas? Based on the requirements document, it should be scrolled down to the latest message.

2021-10-14 06:29 UTC, fauzanlinnas commented
> Have you checked the click-behaviour, Mas @fauzanlinnas? Based on the requirements document, it should be scrolled down to the latest message.

yes mas, itu `onClick`nya bakalan berasal dari Conversation/index.js (pas dipake). Di story sengaja dikosongin cuman buat nampilin UInya doang @suliskh

2021-10-14 06:29 UTC, fauzanlinnas commented on src/rogu/smart-components/Conversation/components/Notification.jsx
> +  timeArray.splice(1, 0, stringSet.CHANNEL__MESSAGE_LIST__NOTIFICATION__ON);
done mas

2021-10-14 09:03 UTC, suliskh requested changes

2021-10-14 09:03 UTC, suliskh commented on src/rogu/smart-components/Conversation/components/stories/index.stories.js
> +import React, { useRef, useState } from "react";
Mas @fauzanlinnas, I think we can put this story inside the existing file (i.e. `.src/rogu/smart-components/Conversation/stories/index.stories.js`).

Also, please add the localization example in that story. You can refer to this: https://sendbird.com/docs/uikit/v1/react/guides/text-localization.

Thank you

2021-10-15 07:20 UTC, fauzanlinnas commented on src/rogu/smart-components/Conversation/components/stories/index.stories.js
> +import React, { useRef, useState } from "react";
mas, ku kurang paham maksud mas yang mesti di localization string yg mana ya?

2021-10-15 07:33 UTC, suliskh commented on src/rogu/smart-components/Conversation/components/stories/index.stories.js
> +import React, { useRef, useState } from "react";
Maksudku ditambahkan contoh localization di storynya Mas @fauzanlinnas. Contohnya seperti di https://github.com/ruang-guru/sendbird-uikit-react/pull/16/files#diff-6f8ab15307cacad99d20adc6c92672595d56164d7fdae9cf8c3b01054c8d928d, aku nambahin contoh override `stringSet`-nya via `<SendbirdProvider stringSet={...}` />. Contoh overridingnya ada di `__mocks__/localizationMock`.

2021-10-18 06:48 UTC, fauzanlinnas commented on src/rogu/smart-components/Conversation/components/stories/index.stories.js
> +import React, { useRef, useState } from "react";
done mas 👍

2021-10-19 02:41 UTC, suliskh commented on src/rogu/smart-components/Conversation/components/stories/index.stories.js
> +import React, { useRef, useState } from "react";
Awraitt, thank you mas

2021-10-19 02:42 UTC, suliskh approved these changes

2021-10-19 02:44 UTC, ibedwi approved these changes
LGTM!🚀

2021-10-19 02:50 UTC, merged