feat: add AssignmentMessageItemBody and MaterialMessageItemBody components
ruang-guru/sendbird-uikit-react pull request #18
Opened 2021-10-18 10:48 UTC by jillyratria

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

## For Internal Contributors

[RKLS-901](https://sendbird.atlassian.net/browse/<RKLS-901>)

## Description Of Changes

Add new component AssignmentMessageItemBody and MaterialMessageItemBody, and integration with MessageContent

AssignmentMessageItemBody
<img width="924" alt="Screen Shot 2021-10-18 at 17 43 30" src="https://user-images.githubusercontent.com/5103456/137716372-306d7a2e-6c57-4a6b-80d6-8a14e7564828.png">

MaterialMessageItemBody
<img width="924" alt="Screen Shot 2021-10-18 at 17 43 24" src="https://user-images.githubusercontent.com/5103456/137716457-7514b658-a529-4713-8a47-05eafc713ce3.png">

2021-10-19 01:34 UTC, suliskh requested changes

2021-10-19 01:34 UTC, suliskh commented on src/rogu/smart-components/Conversation/stories/index.stories.js
> +const appId = "4DE1DD00-7D88-4F55-9C38-F368054928B3";
Is this intentionally replaced with a hardcoded values, Mbak @jillyratria?

2021-10-19 01:34 UTC, suliskh commented on src/rogu/ui/AssignmentMessageItemBody/index.tsx
> +        onClick={openAssignment}>
Because this is an interactive element, I think it would be better to use the semantic element (i.e. `button`). But, if we won't bother to reset the default styling of `button` and keep using `div` instead, we would need to add some `aria`, `role`, and `tabIndex` attributes to make sure that it's accessible and keyboard friendly like a normal button. We can refer to the [`rogu/TextButton`](https://github.com/ruang-guru/sendbird-uikit-react/tree/rogu/v1/src/rogu/ui/TextButton) implementation

2021-10-19 01:34 UTC, suliskh commented on src/rogu/ui/AssignmentMessageItemBody/index.tsx
> +            <Label className="rogu-assignment-message-item-body__text-title" color={LabelColors.ONBACKGROUND_2} type={LabelTypography.BODY_2}>
Have you handled a long title with ellipsis, Mbak @jillyratria ?

2021-10-19 01:34 UTC, suliskh commented on src/rogu/ui/AssignmentMessageItemBody/stories/AssignmentMessageItemBody.stories.js
> +const mockMessage = (process) => {
I saw you have added the mocked message for assignment in `__mocks__/`, but is there any reason to use this locally declared `mockMessage()` function instead of the mock data from the `__mocks__/`, Mbak?

2021-10-19 01:34 UTC, suliskh commented on src/rogu/ui/MaterialMessageItemBody/index.tsx
> +          <div>
Since it only contains a single child, is there any consideration wrap it in a `div`, Mbak @jillyratria?

2021-10-19 01:34 UTC, suliskh commented on src/rogu/ui/TextMessageItemBody/stories/TextMessageItemBody.stories.js
> +<<<<<<< HEAD
I think there is some conflict here, Mbak 🙏🏻

2021-10-19 01:34 UTC, suliskh commented on src/rogu/ui/MaterialMessageItemBody/stories/MaterialMessageItemBody.stories.js
> +const mockMessage = (process) => {
I saw you have added the mocked message for material in `__mocks__/`, but is there any reason to use this locally declared `mockMessage()` function instead of the mock data from the `__mocks__/`, Mbak?

2021-10-19 01:43 UTC, suliskh requested changes

2021-10-19 01:43 UTC, suliskh commented on src/rogu/ui/AssignmentMessageItemBody/index.scss
> +  &.outgoing {
Complying with the BEM convention, should we make it `.rogu-assignment-message-item-body--outgoing` and `.rogu-assignment-message-item-body--incoming`, Mbak @jillyratria?

2021-10-19 01:43 UTC, suliskh commented on src/rogu/ui/AssignmentMessageItemBody/index.scss
> +    .rogu-assignment-message-item-body__text-title {
Should we handle the long title with ellipsis, Mbak @jillyratria?

2021-10-19 09:05 UTC, jillyratria commented on src/rogu/ui/AssignmentMessageItemBody/stories/AssignmentMessageItemBody.stories.js
> +const mockMessage = (process) => {
gak ada sih. `mockMessage()` ku pake di `AssignmentMessageItemBody.stories.js` (aku copy dari `src/ui/OGMessageItemBody.stories.js`. 

Yang `__mocks__/` dipake untuk di stories `MessageContent` ngikut yang udah ada dari @suliskh

2021-10-19 09:09 UTC, jillyratria commented on src/rogu/ui/AssignmentMessageItemBody/index.scss
> +  &.outgoing {
ini ngikut styling yang udah ada di sendbird @suliskh

2021-10-19 09:52 UTC, suliskh commented on src/rogu/ui/AssignmentMessageItemBody/stories/AssignmentMessageItemBody.stories.js
> +const mockMessage = (process) => {
Okay mbak, understand 👍🏻 . The only thing I am wondering is the `process` arg, what is this used for?

2021-10-19 10:05 UTC, suliskh commented on src/rogu/ui/AssignmentMessageItemBody/index.scss
> +  &.outgoing {
Got it, Mbak @jillyratria. Di sisi lain, di codebase sendbird ini juga ternyata masih ada yg ndak tentu konvensinya. Misalnya saja di https://github.com/ruang-guru/sendbird-uikit-react/blob/rogu/v1/src/ui/MessageInput/index.scss yang penggunaannya `--` dan `__` tidak sesuai dengan konvensi BEM yg banyak digunakan di komponen2 lainnya.

Untuk menyeragamkan, aku usul agar disesuaikan dengan konvensi BEM. Dan aku rasa tidak membutuhkan effort yang terlalu besar untuk hal tsb, apalagi jika dilakukan dengan gradual di `src/rogu` saja. We also have prior discussion [here](https://ruangguru.slack.com/archives/G013CQ8KZPF/p1633677090001800). What do you think, Mbak?

2021-10-22 03:51 UTC, suliskh approved these changes

2021-10-22 03:53 UTC, merged