feat(component): add FileViewer component
ruang-guru/sendbird-uikit-react pull request #24
Opened 2021-10-22 04:01 UTC by fauzanlinnas

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

## Related Issue

[RKLS-965](https://ruanggguru.atlassian.net/browse/RKLS-965)
[RKLS-966](https://ruanggguru.atlassian.net/browse/RKLS-966)
[RKLS-967](https://ruanggguru.atlassian.net/browse/RKLS-967)
[RKLS-986](https://ruanggguru.atlassian.net/browse/RKLS-986)

## Description Of Changes
- [x] Design based on figma
- [x] Hide caption when focus on media
- [x] Clamped message when it is too long
- [x] Make Toast component

https://user-images.githubusercontent.com/26358930/138391473-a50e49d0-3110-4047-a2a0-1b51dbe258ae.mp4

2021-10-22 04:17 UTC, jillyratria commented on src/lib/Sendbird.jsx
> +    'rogu-toast-root',
eh, jadinya udah ke root?

2021-10-22 06:52 UTC, suliskh requested changes

2021-10-22 06:52 UTC, suliskh commented on src/rogu/ui/FileViewer/index.jsx
> +const ContentCaption = ({ captionMsg, isHidden }) => {
Why don't we use the `TextMessageItemBody` directly here, Mas @fauzanlinnas?

2021-10-22 06:52 UTC, fauzanlinnas commented on src/lib/Sendbird.jsx
> +    'rogu-toast-root',
yes mbaak @jillyratria

2021-10-22 06:54 UTC, fauzanlinnas commented on src/rogu/ui/FileViewer/index.jsx
> +const ContentCaption = ({ captionMsg, isHidden }) => {
Karena context pemakaiannya beda mas, walaupun ada fitur yg sama
Trus stylingnya juga lumayan beda

2021-10-22 08:11 UTC, suliskh requested changes

2021-10-22 08:11 UTC, suliskh commented on src/rogu/ui/FileViewer/index.jsx
> +const ContentCaption = ({ captionMsg, isHidden }) => {
Klo misal fiturnya sama, menurutku bisa dipakai `TextMessageItemBody`. Karena itulah tujuannya dibuat abstraksi, biar bisa reusable.

Tpi klo memang mau dipisah, mungkin seharusnya tidak memakai `.rogu-text-message-item-body` yah mas. Hal itu akan membuat komponen ini terikat secara implisit dengan `TextMessageItemBody`. Apabila `TextMessageItemBody` tidak ter-import dimanapun di aplikasinya, maka style-nya juga tidak termuat.

2021-10-22 08:16 UTC, suliskh requested changes

2021-10-22 08:16 UTC, suliskh commented on src/rogu/ui/FileViewer/index.scss
> +  z-index: 100000;
To avoid conflicts, I have the z-indexes specified in [src/styles/_z-indexes.scss](https://github.com/ruang-guru/sendbird-uikit-react/blob/rogu/v1/src/styles/_z-indexes.scss) (based on https://mui.com/customization/z-index). I think we can use the `$drawer` here or add another value if needed, Mas @fauzanlinnas

2021-10-22 08:29 UTC, fauzanlinnas commented on src/rogu/ui/FileViewer/index.jsx
> +const ContentCaption = ({ captionMsg, isHidden }) => {
hmm i see
okeh mas, makasih masukannya
kalo gitu ku pake `TextMessageItemBody` 👍

2021-10-22 08:31 UTC, fauzanlinnas commented on src/rogu/ui/FileViewer/index.scss
> +  z-index: 100000;
siap mas

2021-10-22 10:02 UTC, fauzanlinnas commented on src/rogu/ui/FileViewer/index.scss
> +  z-index: 100000;
done mas @suliskh

2021-10-25 00:51 UTC, suliskh commented on src/rogu/ui/FileViewer/index.jsx
> +const ContentCaption = ({ captionMsg, isHidden }) => {
LGTM, Mas @fauzanlinnas! Nitip dihapus commented codenya yah, thank youu

2021-10-25 03:40 UTC, fauzanlinnas commented on src/rogu/ui/FileViewer/index.jsx
> +const ContentCaption = ({ captionMsg, isHidden }) => {
sip maass, sengaja biar direview dulu itu
thank you maas @suliskh

2021-10-25 03:50 UTC, suliskh approved these changes

2021-10-25 03:50 UTC, suliskh commented
LGTM mas @fauzanlinnas ! Thank you

2021-10-25 03:51 UTC, merged