feat(component): add a confirmation modal of delete chat
ruang-guru/sendbird-uikit-react pull request #29
Opened 2021-10-25 09:34 UTC by fauzanlinnas

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

## Related Issue

[RKLS-970](https://ruanggguru.atlassian.net/browse/RKLS-970)

## Description Of Changes
Styling modal based on figma
<img width="852" alt="Screen Shot 2021-10-25 at 16 27 35" src="https://user-images.githubusercontent.com/26358930/138671729-50d3b032-e5ba-4187-b504-f2c9ad4ba924.png">

2021-10-25 10:22 UTC, suliskh requested changes

2021-10-25 10:22 UTC, suliskh commented on src/rogu/ui/Button/index.scss
> +  flex: 1 1 0;
This button component won't always be a flex item, so I think we can omit this `flex: 1 1 0` declaration. 
Instead, we can pass the style via its usage: `<Button className="some-flex-item-styling" />`.

2021-10-25 10:22 UTC, suliskh commented on src/rogu/ui/Button/index.scss
> +.rogu-button--big {
Complying with the BEM convention, I think we need to put the Modifier inside the main class:
```
.rogu-button {
   &.rogu-button--big {...}
}
```

So it would be yielding something like: 
```
.rogu-button.rogu-button--big { ... }
```

2021-10-25 10:22 UTC, suliskh commented on src/rogu/ui/Modal/index.scss
> +  z-index: 10000;
Hi, Mas @fauzanlinnas, would you mind putting this to the `z-indexes.scss` to avoid conflicts?

2021-10-25 10:22 UTC, suliskh commented on src/rogu/ui/Modal/index.scss
> +  z-index: 10001;
Hi, Mas @fauzanlinnas, would you mind putting this to the `z-indexes.scss` to avoid conflicts? 

FWIW, we can use some arithmetic here: `z-index: $someVar + 1`

2021-10-26 04:03 UTC, fauzanlinnas commented on src/rogu/ui/Modal/index.scss
> +  z-index: 10001;
oiya ga liat itu, wokeh siap mas @suliskh

2021-10-26 06:25 UTC, fauzanlinnas commented on src/rogu/ui/Button/index.scss
> +.rogu-button--big {
wha iya oke mas, itu bawaan dari uikit gaada ku ubah wkwk
tengkyu mas dah ngecek 👍

2021-10-26 10:44 UTC, suliskh approved these changes

2021-10-26 10:44 UTC, merged