fix: prevent thumbnail click behaviour if the message is not sent yet
ruang-guru/sendbird-uikit-react pull request #33
Opened 2021-10-28 09:22 UTC by fauzanlinnas

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

## Related Issue
- Error in lms-web, bubble menu dropdown cause error
[slack thread](https://ruangguru.slack.com/archives/G013CQ8KZPF/p1635408941001500)
- FileViewer error when clicking thumbnail of a message that is still in sending state

## Description Of Changes
- [x] Check `setSupposedHover`
- [x] Disable thumbnail onClick when still sending

2021-10-28 09:59 UTC, suliskh requested changes

2021-10-28 09:59 UTC, suliskh commented on src/rogu/ui/MessageContent/index.tsx
> +                    isClickable={getOutgoingMessageState(channel, message) !== OutgoingMessageStates.PENDING}
Instead of using PENDING, what if we use SENT instead? That will guarantee that the message has sent

2021-10-28 11:25 UTC, fauzanlinnas commented on src/rogu/ui/MessageContent/index.tsx
> +                    isClickable={getOutgoingMessageState(channel, message) !== OutgoingMessageStates.PENDING}
jadi errornya tuh kalo dia masih **PENDING**, kalo di click thumbnail dan masuk `FileViewer`, ada error `profileUrl`-nya `undefined`
udah dicek sih kalo state **FAILED** ga error
tapi lebih make sense kalo udah **SENT** ya, ku ganti jadi **SENT** deh
thank you masukannya mas kukuh 👍 @suliskh

2021-10-29 02:01 UTC, suliskh approved these changes
🪥🪥🪥🪥🪥

2021-10-29 02:02 UTC, merged