fix: remove Thumbnail max-width and move Thumbnail and FileViewer utils to rogu/utils
ruang-guru/sendbird-uikit-react pull request #37
Opened 2021-10-29 08:31 UTC by fauzanlinnas

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

## Description Of Changes

- [x] Remove max-width of thumbnail
- [x] Set `SUPPORTED_MIMES` to match PRD
- [x] Move `thumbnail` and `FileViewer` utils to `rogu/utils`

## Demo
Demo thumbnail dan viewer
https://user-images.githubusercontent.com/26358930/139403767-d7762f62-4ff8-4fc2-81d5-8793dfaa6f32.mp4

Demo upload

https://user-images.githubusercontent.com/26358930/139404178-282591d7-4d2d-4d73-8eb0-9eb00de02c0e.mp4

2021-10-29 09:04 UTC, suliskh requested changes

2021-10-29 09:04 UTC, suliskh commented on src/rogu/utils/messageType.ts
> +import { isSupportedFileView } from ".";
I am wondering what is `"."` refers to, Mas @fauzanlinnas ?

2021-10-29 12:58 UTC, fauzanlinnas commented on src/rogu/utils/messageType.ts
> +import { isSupportedFileView } from ".";
wkwk itu otomatis, kayanya ngerefer ke index yg setara file itu, ku specify deh

2021-10-29 13:01 UTC, fauzanlinnas commented on src/rogu/utils/messageType.ts
> +import { isSupportedFileView } from ".";
done mas @suliskh

2021-11-01 02:12 UTC, suliskh approved these changes

2021-11-01 02:12 UTC, merged