feat: add from=chatroom query and menu item 'View'
ruang-guru/sendbird-uikit-react pull request #39
Opened 2021-11-01 13:26 UTC by jillyratria

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

## Description Of Changes

- [ X]  show menu item view on file message

![Screen Shot 2021-11-01 at 20 23 42](https://user-images.githubusercontent.com/5103456/139678763-4ad05e71-72f6-4282-a31d-ae238ed2c6b4.png)

- [ X]  show menu item view on thumbnail message
![Screen Shot 2021-11-01 at 20 23 53](https://user-images.githubusercontent.com/5103456/139678797-9b24f7c6-5493-4c45-9276-bda66d1a4dc1.png)

- [ X]  add query `from=chatroom` assignment and material open

2021-11-02 05:44 UTC, suliskh requested changes

2021-11-02 05:44 UTC, suliskh commented on src/rogu/ui/MaterialMessageItemBody/index.tsx
> +      window.open(`${materialData?.ctaWeb}?from=chatroom`);
Mbak @jillyratria, nuwun sewu ini apakah tidak disamakan dengan payload tracker-nya saja mbak? I.e. `obrolan_kelas`

2021-11-02 05:44 UTC, suliskh commented on src/rogu/ui/MessageInput/index.jsx
> +        elem.style.height = `${LINE_HEIGHT}px`;
I am wondering if `elem.style` will yielding an error because `elem` object is possibly nullish, Mbak?

2021-11-02 09:47 UTC, jillyratria commented on src/rogu/ui/MaterialMessageItemBody/index.tsx
> +      window.open(`${materialData?.ctaWeb}?from=chatroom`);
yang di tracker-nya Ibe, pake `chatroom` Kuh. Pake yang `chatroom` dulu. Yang di tracker nya chatroom nanti di-update.

2021-11-03 05:12 UTC, suliskh commented on src/rogu/ui/MaterialMessageItemBody/index.tsx
> +      window.open(`${materialData?.ctaWeb}?from=chatroom`);
Awraitt mbak jill. Suwunn. Nice work 🔥

2021-11-03 08:01 UTC, jillyratria commented on src/rogu/ui/MessageInput/index.jsx
> +        elem.style.height = `${LINE_HEIGHT}px`;
updated ya @suliskh, maacih udah dilihat~~

2021-11-03 10:14 UTC, suliskh approved these changes
Great work!

2021-11-03 10:21 UTC, merged