feat(component):  link preview before sending a link
ruang-guru/sendbird-uikit-react pull request #40
Opened 2021-11-01 19:26 UTC by jillyratria

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

## Related Issue

[RKLS-903](https://ruanggguru.atlassian.net/browse/RKLS-903)

## Description Of Changes
![Screen Shot 2021-11-02 at 02 25 45](https://user-images.githubusercontent.com/5103456/139729341-87633962-da59-45ea-9c78-316dc52428a4.png)

https://user-images.githubusercontent.com/5103456/139729156-0dc929b4-11dc-4939-a3de-d1d919c71408.mov

https://user-images.githubusercontent.com/5103456/139729199-df9e3272-fffc-45d7-a16e-824d8da9cf7e.mov

2021-11-02 04:18 UTC, suliskh requested changes

2021-11-02 04:18 UTC, suliskh commented on src/rogu/ui/MessageInput/index.jsx
> +      createdAt: 2000000,
Mbak @jillyratria , is this expectedly harcoded? What if we use something like: `new Date().getTime()`?

2021-11-02 04:18 UTC, suliskh commented on src/rogu/ui/OGMessageItemBody/index.tsx
> +  closePreview,
To comply with the existing convention, I think we should use `on` prefix in a callback prop

2021-11-02 04:18 UTC, suliskh commented on src/rogu/ui/MessageInput/index.jsx
> +      return <p>Loading</p>;
I think we should put this into the `stringSet` to be configurable.
Also, what do you think if we use `<Label />` component instead of `<p />` tag here, Mbak?

2021-11-03 04:29 UTC, jillyratria commented on src/rogu/ui/MessageInput/index.jsx
> +      createdAt: 2000000,
iya hardcoded.  dan sengaja. karena sebenarnya gak dipake. jadi ambil konstanta aja.

2021-11-03 05:14 UTC, suliskh approved these changes

2021-11-03 05:17 UTC, merged