Lms/pull from sendbird v270
ruang-guru/sendbird-uikit-react pull request #93
Opened 2022-04-26 09:48 UTC by fauzanlinnas

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

## Related Issue

[<JIRA_CARD>](https://ruanggguru.atlassian.net/browse/<JIRA_CARD>)

## Description Of Changes

Add a brief description of the changes that you have involved in this PR

### Technical Approach

### Additional Changes

### Demo

2022-04-26 10:09 UTC, fauzanlinnas commented
oiya blm cek snapshotnya

2022-04-26 21:00 UTC, suliskh commented
> oiya blm cek snapshotnya

There're failing tests that block the merging, Mas @fauzanlinnas. Pls fix that yah :sungkem:

2022-04-27 05:29 UTC, fauzanlinnas commented
> > oiya blm cek snapshotnya
> 
> There're failing tests that block the merging, Mas @fauzanlinnas. Pls fix that yah :sungkem:

ku bingung nih kenapa
kalo jalanin `npm run test` di local berhasil semua, tapi di githubnya ngga @suliskh 

![image](https://user-images.githubusercontent.com/26358930/165447323-737134e1-304b-40bc-89c8-db8e41f9bc5e.png)

2022-04-27 06:58 UTC, suliskh requested changes

2022-04-27 06:58 UTC, suliskh commented on package.json
> +    "react": "^17.0.2",
Dicoba `react-test-renderer`, `react`, `react-dom`-nya tetep versi yg 16 yaa. Karena di Ruangkelas juga masih pakai 16

2022-04-27 08:13 UTC, suliskh commented on src/rogu/ui/FileMessageItemBody/__tests__/FileMessageItemBody.spec.js
> +const createMockMessage = (process) => {
Is it expected changes?

2022-04-27 08:14 UTC, suliskh commented on rollup.config.js
> -      dir: 'release/dist/cjs',
I think it is better to not change the build path. Make sure there's no regression by installing it in Ruangkelas

2022-04-28 07:42 UTC, fauzanlinnas commented on src/rogu/ui/FileMessageItemBody/__tests__/FileMessageItemBody.spec.js
> +const createMockMessage = (process) => {
deleted karena ngga kepake

2022-04-28 07:42 UTC, fauzanlinnas commented on rollup.config.js
> -      dir: 'release/dist/cjs',
all path revert to ruangkelas config

2022-04-29 06:43 UTC, suliskh commented
Letsgoo 🚀 

Sebelum rilis, minta tolong dicoba build dan pasang di Ruangkelas yah mas :sungkem:

2022-04-29 06:43 UTC, suliskh approved these changes

2022-04-29 06:43 UTC, merged