release: v1.2.0
ruang-guru/sendbird-uikit-react pull request #95
Opened 2022-04-29 08:32 UTC by fauzanlinnas

> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

Release  `v1.2.0` with added `copy-css.sh`

2022-04-29 08:37 UTC, suliskh requested changes

2022-04-29 08:37 UTC, suliskh commented on CHANGELOG.md
> +## [1.2.1](Apr 22 2022)
Pls mind the release date-nya yah mas :sungkem:

2022-04-29 09:00 UTC, fauzanlinnas commented on CHANGELOG.md
> +## [1.2.1](Apr 22 2022)
udaaahh, typo tadi wkwk

2022-05-09 02:55 UTC, suliskh requested changes

2022-05-09 02:55 UTC, suliskh commented on CHANGELOG.md
> +- Feature
According to [our internal convention](https://github.com/ruang-guru/sendbird-uikit-react/tree/rogu/v1/internal_docs)` it should be a "Chore" instead of "Features" yah mas

2022-05-09 03:44 UTC, fauzanlinnas commented on CHANGELOG.md
> +- Feature
done

2022-05-09 06:20 UTC, suliskh approved these changes
NTAPSS.. Kapalkan 🚢 !

2022-05-09 06:20 UTC, merged